from dataclasses import dataclass, field
from typing import Any


@dataclass(slots=True)
class KnowledgeRequest:
    """
    A normalized request for external knowledge.

    Generated by the Brain after intent classification.
    """

    query: str

    category: str = "general"

    location: str | None = None

    language: str = "en"

    realtime: bool = True

    max_sources: int = 5

    metadata: dict[str, Any] = field(default_factory=dict)