"""
MYRAA Cognitive Engine

Execution Plan
"""

from __future__ import annotations

import time

from dataclasses import dataclass, field
from enum import Enum
from typing import Any

from ...semantic.semantic_models import SemanticTask
from ..models.plan_step import PlanStep


class PlanStatus(str, Enum):
    """
    Overall execution plan state.
    """

    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"


@dataclass(slots=True)
class ExecutionPlan:
    """
    Complete executable plan generated by the planner.
    """

    # =====================================================
    # Source Task
    # =====================================================

    task: SemanticTask

    # =====================================================
    # Steps
    # =====================================================

    steps: list[PlanStep] = field(default_factory=list)

    current_step_index: int = 0

    estimated_steps: int = 0

    # =====================================================
    # Status
    # =====================================================

    status: PlanStatus = PlanStatus.PENDING

    successful: bool = True

    reason: str = ""

    # =====================================================
    # Timing
    # =====================================================

    created_at: float = field(default_factory=time.time)

    started_at: float | None = None

    finished_at: float | None = None

    execution_time: float = 0.0

    # =====================================================
    # Metadata
    # =====================================================

    metadata: dict[str, Any] = field(default_factory=dict)

    # =====================================================
    # Lifecycle
    # =====================================================

    def start(self) -> None:
        self.status = PlanStatus.RUNNING
        self.started_at = time.perf_counter()

    def complete(self) -> None:
        self.status = PlanStatus.COMPLETED
        self.finished_at = time.perf_counter()

        if self.started_at is not None:
            self.execution_time = (
                self.finished_at - self.started_at
            )

    def fail(self, reason: str = "") -> None:
        self.status = PlanStatus.FAILED
        self.successful = False
        self.reason = reason
        self.finished_at = time.perf_counter()

        if self.started_at is not None:
            self.execution_time = (
                self.finished_at - self.started_at
            )

    def cancel(self) -> None:
        self.status = PlanStatus.CANCELLED
        self.successful = False
        self.finished_at = time.perf_counter()

        if self.started_at is not None:
            self.execution_time = (
                self.finished_at - self.started_at
            )

    # =====================================================
    # Step Management
    # =====================================================

    def add_step(self, step: PlanStep) -> None:
        self.steps.append(step)
        self.estimated_steps = len(self.steps)

    def insert_step(
        self,
        index: int,
        step: PlanStep,
    ) -> None:
        self.steps.insert(index, step)
        self.estimated_steps = len(self.steps)

    def remove_step(self, index: int) -> None:
        del self.steps[index]
        self.estimated_steps = len(self.steps)

    # =====================================================
    # Navigation
    # =====================================================

    @property
    def active_step(self) -> PlanStep | None:
        if self.current_step_index >= len(self.steps):
            return None

        return self.steps[self.current_step_index]

    def next_step(self) -> PlanStep | None:
        self.current_step_index += 1
        return self.active_step

    # =====================================================
    # Statistics
    # =====================================================

    @property
    def total_steps(self) -> int:
        return len(self.steps)

    @property
    def completed_steps(self) -> int:
        return sum(step.completed for step in self.steps)

    @property
    def failed_steps(self) -> int:
        return sum(step.failed for step in self.steps)

    @property
    def progress(self) -> float:
        if not self.steps:
            return 0.0

        return self.completed_steps / len(self.steps)

    # =====================================================
    # Queries
    # =====================================================

    @property
    def is_empty(self) -> bool:
        return not self.steps

    @property
    def is_finished(self) -> bool:
        return self.status in (
            PlanStatus.COMPLETED,
            PlanStatus.FAILED,
            PlanStatus.CANCELLED,
        )

    # =====================================================
    # Reset
    # =====================================================

    def reset(self) -> None:
        self.status = PlanStatus.PENDING
        self.successful = True
        self.reason = ""

        self.current_step_index = 0

        self.started_at = None
        self.finished_at = None
        self.execution_time = 0.0

        for step in self.steps:
            step.reset()